runtime: python39

entrypoint: gunicorn -b :$PORT setup.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "setup.settings"
  SECRET_KEY: django-insecure-9ty33rrr@=ckr=57kxdp%ph($(c$mny7a7*t+tu01m#w(_27_2
  DEBUG: "False"
  ALLOWED_HOSTS: ["https://igneous-shell-424923-t6.uc.r.appspot.com"]

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
